### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by loriab** [psi4/erd#1]
There's traces of GPL2+ in source code, so I added that license, but it'd be nice to know where the source came from and get the license and just of the project direct. Only trace of it I see on GH is Chow's https://github.com/hpcgarage/OptErd .
- [ ] inform authors of this hosting and CMake build scheme.
- [ ] inform authros of imminent conda package. @loriab has talking points, if required
- [ ] find out what version the authors (N. FLOCKE, V. LOTRICH) consider this to be. Replace the 9.9.9 in main CMakeLists.txt with that value
- [ ] find out what they consider the name of the project to be: `ERD`, `erd`, `liberd`, `LibERD`, etc. On the Psi4 side, it's not too late to change the repo and target names.

**Comment by loriab** [comment]
@andysim

**Comment by loriab** [comment]
@bennybp, I started the final naming process on `liberd` to `ERD` on the strength that `ERD` is what they called it in the [paper](http://onlinelibrary.wiley.com/doi/10.1002/jcc.21018/abstract). But then I noticed you called it `liberd` in the simint paper. Do you have any authority for liberd over erd? Or any clue what version erd thinks it is?

**Comment by bennybp** [comment]
Nope. I think I took that naming convention from Psi4. I suppose it can make sense since you could imagine it as ERD while in ACES, but libERD when outside. But that's probably overthinking it.

And no clue about the version either. I don't think I could ever find an official download.

**Comment by loriab** [comment]
Ok, thanks. I've got it everywhere as `erd` now, so it's going to stay that way unless a real live author shows up. I've found a repo of it _in_ AcesIII, but not indep.

**Comment by loriab** [comment]
As I understand it, the erd authors don't welcome contact. So settling on name `erd`, version of AcesIII, and license included in AcesIII.
